### ISSUE TITLE
Custom Client Names addition

### ISSUE THREAD

**Issue by asaddon** [Xentrk/Asuswrt-Merlin-Linux-Shell-Scripts#6]
Hey can you add a function to save and restore custom Client Names as well because right now it's only saving DHCP static list and we still have to manually enter all the custom names we set for them.

**Comment by Xentrk** [comment]
I need some clarification please to help point me in the right direction.  What nvram field or screen are the Client Names configured in?  I am only aware of setting the name for LAN clients in the LAN -> DHCP Server screen.

**Comment by asaddon** [comment]
The key for that is:
nvram get custom_clientlist

Rest of the backup and restore procedure is same.

**Comment by asaddon** [comment]
And to change edit the names in web UI go to DHCP LAN settings page and click on device icons, a pop-up screen will open and you can add names for them.
